package com.ryankshah.skyrimcraft.loot;

import com.ryankshah.skyrimcraft.Constants;
import com.ryankshah.skyrimcraft.registry.ItemRegistry;
import net.fabricmc.fabric.api.loot.v2.LootTableEvents;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

public class SkyrimcraftLootTables
{
    protected static LootPool.Builder villageTable = LootPool.lootPool()
            .setRolls(UniformGenerator.between(1.0F, 5.0F))
            .add(LootItem.lootTableItem(ItemRegistry.GRASS_POD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SWEET_ROLL.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.GARLIC_BREAD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.POTATO_BREAD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.CABBAGE_SOUP.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.CABBAGE_POTATO_SOUP.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.DWARVEN_OIL.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HAWK_EGG.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.BEEF_STEW.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.BEEHIVE_HUSK.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_BOOTS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_CHESTPLATE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_HELMET.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_LEGGINGS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_SWORD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HUNTING_BOW.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.LONGBOW.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.ALE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.ALTO_WINE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.ARGONIAN_ALE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SKOOMA.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.WINE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.FIREBRAND_WINE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SPICED_WINE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.FLOUR.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.BUTTER.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.MEAD_WITH_JUNIPER_BERRY.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.BLACK_BRIAR_MEAD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.DRAGONS_BREATH_MEAD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HONNINGBREW_MEAD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.NORD_MEAD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HORSE_HAUNCH.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HORSE_MEAT.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.VEGETABLE_SOUP.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.LEG_OF_GOAT_ROAST.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.LEG_OF_GOAT.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.GOURD.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SLICED_EIDAR_CHEESE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SLICED_GOAT_CHEESE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.CHICKEN_DUMPLING.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.APPLE_DUMPLING.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.LEATHER_STRIPS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SALT_PILE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.DEATHBELL.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.CRIMSON_NIRNROOT.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.BEEHIVE_HUSK.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.TAPROOT.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HIDE_LEGGINGS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HIDE_HELMET.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HIDE_CHESTPLATE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HIDE_BOOTS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SCALED_BOOTS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SCALED_CHESTPLATE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SCALED_LEGGINGS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.SCALED_HELMET.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.HUNTING_BOW.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.LONGBOW.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.STORMCLOAK_OFFICER_BOOTS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.STORMCLOAK_OFFICER_CHESTPLATE.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.STORMCLOAK_OFFICER_HELMET.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            )
            .add(LootItem.lootTableItem(ItemRegistry.STORMCLOAK_OFFICER_LEGGINGS.get())
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
            );

    public static void addLootTables() {
        LootPool.Builder watchtowerTable = LootPool.lootPool()
                .setRolls(UniformGenerator.between(1.0F, 4.0F))
                .add(LootItem.lootTableItem(ItemRegistry.VAMPIRE_DUST.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SWEET_ROLL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.GARLIC_BREAD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.POTATO_BREAD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CABBAGE_SOUP.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CABBAGE_POTATO_SOUP.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CHARRED_SKEEVER_HIDE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SALT_PILE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TROLL_FAT.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.BEAR_CLAWS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_BOOTS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_CHESTPLATE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_HELMET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_LEGGINGS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.IMPERIAL_SWORD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HUNTING_BOW.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.LONGBOW.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_RUBY.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_EMERALD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_DIAMOND.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWLESS_RUBY.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_GARNET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWLESS_GARNET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_AMETHYST.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))));

        LootPool.Builder dungeonTable = LootPool.lootPool()
                .setRolls(UniformGenerator.between(1.0F, 4.0F))
                .add(LootItem.lootTableItem(ItemRegistry.VAMPIRE_DUST.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FIRE_SALTS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SALT_PILE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.DWARVEN_OIL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TROLL_FAT.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TAPROOT.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.BEAR_CLAWS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CHARRED_SKEEVER_HIDE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.BRIAR_HEART.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.DWARVEN_OIL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.DWARVEN_METAL_INGOT.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_BATTLEAXE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_BOOTS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_BOW.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_CHESTPLATE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_GREATSWORD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_HELMET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_LEGGINGS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_SWORD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_WAR_AXE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.PHILTER_OF_THE_PHANTOM_POTION.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.POTION_OF_WATERWALKING.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_RUBY.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_EMERALD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_DIAMOND.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWLESS_RUBY.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_GARNET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWLESS_GARNET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_AMETHYST.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))))
                .add(LootItem.lootTableItem(ItemRegistry.TOMATO_SEEDS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CABBAGE_SEEDS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ASH_YAM_SLIPS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.GARLIC.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SWEET_ROLL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                );

        LootPool.Builder altarTable = LootPool.lootPool()
                .setRolls(UniformGenerator.between(1.0F, 3.0F))
                .add(LootItem.lootTableItem(Items.CANDLE)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1F, 3.0F)))
                )
                .add(LootItem.lootTableItem(Items.BLACK_CANDLE)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1F, 3.0F)))
                )
                .add(LootItem.lootTableItem(Items.REDSTONE)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4F, 6.0F)))
                )
                .add(LootItem.lootTableItem(Items.CHAIN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2F, 6.0F)))
                )
                .add(LootItem.lootTableItem(Items.EMERALD)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1F, 4.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SWEET_ROLL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.GARLIC.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HIDE_BOOTS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HIDE_CHESTPLATE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HIDE_HELMET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HIDE_LEGGINGS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HUNTING_BOW.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.LONGBOW.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_HELMET.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_LEGGINGS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_SWORD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ANCIENT_NORD_WAR_AXE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.PHILTER_OF_THE_PHANTOM_POTION.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FLAWED_EMERALD.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F))));

        LootPool.Builder chestPool = LootPool.lootPool()
                .setRolls(UniformGenerator.between(1.0F, 3.0F))
                .add(LootItem.lootTableItem(ItemRegistry.VAMPIRE_DUST.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FIRE_SALTS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SALT_PILE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.DWARVEN_OIL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TROLL_FAT.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TAPROOT.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.BEAR_CLAWS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CHARRED_SKEEVER_HIDE.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 3.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.BRIAR_HEART.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 2.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CONJURE_FAMILIAR_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CONJURE_ZOMBIE_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FIREBALL_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.DETECT_LIFE_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.LIGHTNING_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TURN_UNDEAD_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.HEALING_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.FLAME_CLOAK_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.OAKFLESH_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TELEKINESIS_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CANDLELIGHT_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ICE_SPIKE_SPELLBOOK.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.TOMATO_SEEDS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.CABBAGE_SEEDS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.ASH_YAM_SLIPS.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.GARLIC.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                )
                .add(LootItem.lootTableItem(ItemRegistry.SWEET_ROLL.get())
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                );


        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (
                    lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "grasspod")))
            )) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.GRASS_POD.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.875F, 1.0F)))
                            )
                    );
            }
        });

        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "oregemdrops"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(UniformGenerator.between(0.125F, 1.0F))
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWED_RUBY.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            )
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWED_EMERALD.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            )
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWED_DIAMOND.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            )
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWLESS_RUBY.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            )
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWED_GARNET.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            )
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWLESS_GARNET.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            )
                            .add(LootItem.lootTableItem(ItemRegistry.FLAWED_AMETHYST.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.25F, 1.0F)))
                            ));
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "beehive"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.BEEHIVE_HUSK.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.45f, 1.0F)))
                            )
                    );
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "spider"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.SPIDER_EGG.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.45f, 1.0F)))
                            )
                    );
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "salmon"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.SALMON_ROE.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.45f, 1.0F)))
                            )
                    );
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "bee"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.BEE.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.875F, 1.0F)))
                            )
                    );
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "evoker"))))) {
                lootBuilder.withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1))
                        .add(LootItem.lootTableItem(ItemRegistry.CONJURE_FAMILIAR_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.CONJURE_ZOMBIE_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.FIREBALL_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.DETECT_LIFE_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.LIGHTNING_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.TURN_UNDEAD_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.HEALING_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.FLAME_CLOAK_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.OAKFLESH_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.TELEKINESIS_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.CANDLELIGHT_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.ICE_SPIKE_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                );
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "witch"))))) {
                lootBuilder.withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1))
                        .add(LootItem.lootTableItem(ItemRegistry.CONJURE_FAMILIAR_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.CONJURE_ZOMBIE_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.FIREBALL_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.DETECT_LIFE_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.LIGHTNING_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.TURN_UNDEAD_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.HEALING_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.FLAME_CLOAK_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.OAKFLESH_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.TELEKINESIS_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.CANDLELIGHT_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.ICE_SPIKE_SPELLBOOK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                );
            }
        });

        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "witch"))))) {
                lootBuilder.withPool(villageTable);
            }
        });

        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/watchtower"))))) {
                lootBuilder.withPool(watchtowerTable);
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/skyrim_dungeon"))))) {
                lootBuilder.withPool(dungeonTable);
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/altar"))))) {
                lootBuilder.withPool(altarTable);
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "goat"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.LEG_OF_GOAT.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.875F, 1.0F)))
                            )
                    );
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "horse"))))) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.HORSE_MEAT.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.875F, 1.0F)))
                            ));
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (
                    lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/simple_dungeon"))) ||
                            lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/abandoned_mineshaft"))) ||
                            lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/buried_treasure"))) ||
                            lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/desert_pyramid"))) ||
                            lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/shipwreck_supply"))) ||
                            lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "chests/stronghold_corridor"))) ||
                            lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "gameplay/piglin_bartering")))
                                    )) {
                    lootBuilder.withPool(LootPool.lootPool()
                            .setRolls(ConstantValue.exactly(1))
                            .add(LootItem.lootTableItem(ItemRegistry.HORSE_MEAT.get())
                                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.875F, 1.0F)))
                            ));
            }
        });
        LootTableEvents.MODIFY.register((lootTableResourceKey, lootBuilder, lootTableSource) -> {
            if (lootTableSource.isBuiltin() && (lootTableResourceKey.equals(ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(Constants.MODID, "gameplay/sniffer_digging"))))) {
                lootBuilder.withPool(LootPool.lootPool()
                        .setRolls(UniformGenerator.between(1.0F, 3.0F))
                        .add(LootItem.lootTableItem(ItemRegistry.TAPROOT.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.FIRE_SALTS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.SALT_PILE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        )
                        .add(LootItem.lootTableItem(ItemRegistry.DWARVEN_OIL.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(0.5F, 1.0F)))
                        ));
            }
        });
    }
}